'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ALMACENES
    Public Property ID_ALM As Integer
    Public Property ID_CTE As Integer
    Public Property NOMBRE As String
    Public Property F_ENTRADA As Nullable(Of Integer)
    Public Property F_SALIDA As Nullable(Of Integer)
    Public Property F_TRANSFERENCIA As Nullable(Of Integer)
    Public Property TIPO As Integer
    Public Property ESTATUS As String

    Public Overridable Property CLIENTES As CLIENTES

End Class
