'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTES
    Public Property ID_CTE As Integer
    Public Property NOMBRE As String
    Public Property MARCA As String
    Public Property DIRECCION As String
    Public Property COLONIA As String
    Public Property MUNICIPIO As String
    Public Property ESTADO As String
    Public Property EMAIL As String
    Public Property TELEFONO As String
    Public Property CELULAR As String
    Public Property CP As String
    Public Property RFC As String
    Public Property ID_TCTE As Integer
    Public Property ESTATUS As String
    Public Property HORA_INI As Nullable(Of System.TimeSpan)
    Public Property HORA_PED As Nullable(Of System.TimeSpan)

    Public Overridable Property ALMACENES As ICollection(Of ALMACENES) = New HashSet(Of ALMACENES)

End Class
