'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TIFMAZATLANEntities3
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TIFMAZATLANEntities3")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ALMACENES() As DbSet(Of ALMACENES)
    Public Overridable Property CLIENTES() As DbSet(Of CLIENTES)
    Public Overridable Property ESPECIES() As DbSet(Of ESPECIES)
    Public Overridable Property FAMILIAS() As DbSet(Of FAMILIAS)

End Class
